version: '3.7'

services:
  phonebook-frontend:
    container_name: phonebook-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'

  phonebook-backend:
    container_name: phonebook-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '3002:3002'